FROM python:3.7-slim
RUN  apt-get clean
RUN  apt-get update && apt-get install -y nginx
ADD gamedata_backup.py /
ADD requirements.txt /
ADD /pro/ssl_cert /ssl_cert
ADD run.sh /
COPY /pro/gamedata_backup.conf /etc/nginx/conf.d/gamedata_backup.conf
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN chmod +x run.sh
EXPOSE 10010
CMD ["./run.sh"]
