FROM python:3.7-slim
RUN  apt-get clean
RUN  apt-get update && apt-get install -y nginx
COPY /pro/login_systeam.conf /etc/nginx/conf.d/login_systeam.conf
ADD /pro/ssl_cert /ssl_cert
ADD run.sh /
RUN chmod +x run.sh
ADD login_systeam.py /
ADD requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 10012
CMD ["./run.sh"]
