FROM python:3.7-slim
RUN  apt-get clean
RUN  apt-get update && apt-get install -y nginx
COPY /pro/user_service.conf /etc/nginx/conf.d/user_service.conf
ADD /pro/ssl_cert /ssl_cert
ADD config  /config
ADD data  /data
ADD service /service
ADD utils /utils
ADD run.sh /
ADD main.py /
ADD requirements.txt /
ADD swagger.yaml  /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN chmod +x run.sh
EXPOSE 10014
CMD [ "./run.sh"]