FROM python:3.7-slim
RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN  sed -i s@/deb.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list
ENV  PIP_SITE http://mirrors.aliyun.com/pypi/simple/
ENV  PIP_HOST mirrors.aliyun.com
RUN  apt-get clean
RUN  apt-get update && apt-get install -y nginx
RUN  apt-get install -y git
RUN  git config --global user.email "you@example.com"
run  git config --global user.name "Your Name"
ADD redeem.py /
ADD requirements.txt /
ADD run.sh /
ADD sandbox/ssl_cert /ssl_cert
COPY sandbox/redeem.conf /etc/nginx/conf.d/redeem.conf
RUN pip install --upgrade pip
RUN pip install -r requirements.txt -i $PIP_SITE --trusted-host $PIP_HOST
RUN chmod +x run.sh
EXPOSE 9989/udp 9989/tcp
VOLUME ["/root/redeemsystem", "/root/operationlives"]
CMD [ "./run.sh"]
