FROM debian
RUN apt-get update 
RUN apt-get -y install git ssh
ADD * ./
RUN mkdir ~/.ssh/
RUN touch ~/.ssh/authorized_keys
RUN touch ~/.ssh/known_hosts
RUN ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
RUN mv id_rsa ~/.ssh/
RUN mv id_rsa.pub ~/.ssh/
RUN chmod 600 ~/.ssh/id_rsa
RUN git clone git@github.com:qinbatista/Config_YoutubeList.git

# CMD [ "python" ,"/photo_manager.py"]