FROM python:3.7-slim
ADD folder_sync.py /
ADD mycert.crt /
ADD requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

VOLUME [ "/Video","/OneDrive"]
WORKDIR /
EXPOSE 10015
CMD ["python3","/folder_sync.py"]
